// <auto-generated />
using System;
using FinanceTracker.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracker.Web.Migrations
{
    [DbContext(typeof(FinanceTrackerDbContext))]
    partial class FinanceTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.CashHoldingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Savings")
                        .HasColumnName("account_type");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("cash_holdings", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.EquityHoldingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_tag");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("AverageBuyPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("average_buy_price");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company_name");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("NSE")
                        .HasColumnName("exchange");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isin");

                    b.Property<DateTime>("LastPriceUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_price_update");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AccountTag");

                    b.ToTable("equity_holdings", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.ExpenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("source");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.MonthlySnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cash_value");

                    b.Property<decimal>("EquityValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("equity_value");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month");

                    b.Property<decimal>("MutualFundValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mutual_fund_value");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date");

                    b.Property<decimal>("TotalCurrentValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_current_value");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_invested");

                    b.Property<decimal>("UsStockValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("us_stock_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Month")
                        .IsUnique();

                    b.ToTable("monthly_snapshots", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.MutualFundHoldingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_tag");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Amc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("amc");

                    b.Property<decimal>("AverageNav")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("average_nav");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<decimal>("CurrentNav")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("current_nav");

                    b.Property<string>("FolioNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("folio_number");

                    b.Property<DateTime>("LastNavUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_nav_update");

                    b.Property<string>("SchemeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scheme_code");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scheme_name");

                    b.Property<decimal>("Units")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("units");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AccountTag");

                    b.ToTable("mutual_fund_holdings", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.UsStockHoldingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("AverageBuyPriceUsd")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("average_buy_price_usd");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company_name");

                    b.Property<decimal>("CurrentPriceUsd")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price_usd");

                    b.Property<decimal>("ExchangeRateUsdInr")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("exchange_rate_usd_inr");

                    b.Property<DateTime>("LastPriceUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_price_update");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("us_stock_holdings", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.CashHoldingEntity", b =>
                {
                    b.HasOne("FinanceTracker.Web.Database.Entities.UserEntity", "User")
                        .WithMany("CashHoldings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.EquityHoldingEntity", b =>
                {
                    b.HasOne("FinanceTracker.Web.Database.Entities.UserEntity", "User")
                        .WithMany("EquityHoldings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("FinanceTracker.Web.Database.Entities.UserEntity", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.MonthlySnapshotEntity", b =>
                {
                    b.HasOne("FinanceTracker.Web.Database.Entities.UserEntity", "User")
                        .WithMany("MonthlySnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.MutualFundHoldingEntity", b =>
                {
                    b.HasOne("FinanceTracker.Web.Database.Entities.UserEntity", "User")
                        .WithMany("MutualFundHoldings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.UsStockHoldingEntity", b =>
                {
                    b.HasOne("FinanceTracker.Web.Database.Entities.UserEntity", "User")
                        .WithMany("UsStockHoldings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracker.Web.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("CashHoldings");

                    b.Navigation("EquityHoldings");

                    b.Navigation("Expenses");

                    b.Navigation("MonthlySnapshots");

                    b.Navigation("MutualFundHoldings");

                    b.Navigation("UsStockHoldings");
                });
#pragma warning restore 612, 618
        }
    }
}
